info:
  version: @pom.version@
  stage: prod

spring:
  profiles:
    active: prod
  devtools:
    livereload:
      enabled: false
      port: 35729
    restart:
      enabled: false
      exclude: static/**,public/**