logging:
  file: logs/spring-boot-admin.log

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:9001
  jackson:
    serialization:
     indent-output: true

endpoints:
  health:
    sensitive: false

server:
  port: 9001